services:
  htmz:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=1234
    ports:
      - "8080:8080"  # Expose for direct testing
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2G
        reservations:
          cpus: '2.0'
          memory: 1G
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  k6:
    image: grafana/k6:latest
    volumes:
      - ./load-test:/scripts
    environment:
      - BASE_URL=http://htmz:8080
    depends_on:
      - htmz
    command: run /scripts/progressive-test.js
    profiles:
      - test
